---
- name: Comprimir contenido de un directorio en tar.gz y borrar lo comprimido
  hosts: "{{server_hostname}}"
  become: true
  gather_facts: false
  vars:

  tasks:
    - name: Comprimir contenido del directorio en tar.gz
      command: "tar -cvzf /var/www/html/contenido$( date '+%Y-%m-%d_%H-%M-%S' ).tar.gz /var/www/html/uploads"

    - name: Borrar archivos originales
      command: "rm -rf /var/www/html/uploads/*"
