---
- name: take snapshot of VM
  hosts: "{{ _host_ }}"
  tasks:
    - name: take snapshot
      amazon.aws.ec2_snapshot:
        instance_id: "{{ _instance_id_ }}"
        region: "{{ _region_ }}"
        wait: false
        snapshot_tags:
          Name: snapshot_of_vm
