---
- name: Crear archivos de 100 MB
  hosts: "{{server_hostname}}"
  become: true
  gather_facts: false
  tasks:
    - name: Crear directorio si no existe
      file:
        path: "/var/www/html/uploads/"
        state: directory

    - name: Crear archivos de logs
      command: "dd if=/dev/zero of=/var/www/html/uploads/file{{ item }}.log bs=1024 count=102400"
      loop: "{{ range(1, 20) | list }}"
  
    - name: nginx fail
      systemd:
        name: nginx
        state: stopped
      
