---
- name: Instalar Nginx 
  hosts: "{{server_hostname}}"
  become: true

  tasks:
    - name: Instalar Nginx
      yum:
        name: nginx
        state: present

    - name: Habilitar y iniciar el servicio Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
  
