---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

     ## Define the conditions we are looking for

  rules:
    - name: Test
      condition: 
        all:
          - event.payload.State == "OPEN"
      action:
        run_job_template:
          name: "setquotas"
          organization: "Default"
